### ISSUE TITLE
An Error has occured. Message:Element databasename is undefined in a CFML structure referenced as part of an expression.  Details:

### ISSUE THREAD

**Issue by EBarber** [tpryan/Apptacular#45]
Apptacular creates an application first time through no problem but when i regenerate I get the above error.

I have the latest version of apptacular
cf 9

**Comment by EBarber** [comment]
log detais for this issue

struct Detail: [empty string] ErrNumber: 0 Message: Element CatcaOffice is undefined in a CFML structure referenced as part of an expression. Resolvedname: [empty string] StackTrace: coldfusion.runtime.UndefinedElementException: Element CatcaOffice is undefined in a CFML structure referenced as part of an expression. at coldfusion.runtime.CfJspPage.ArrayGetAt(CfJspPage.java:961) at coldfusion.runtime.CfJspPage._arrayGetAt(CfJspPage.java:972) at coldfusion.runtime.CfJspPage._arrayGetAt(CfJspPage.java:967) at coldfusion.runtime.CfJspPage._arrayGetAt(CfJspPage.java:677) at coldfusion.runtime.CfJspPage._arrayGetAt(CfJspPage.java:659) at coldfusion.runtime.CfJspPage._arrayGetAt(CfJspPage.java:576) at coldfusion.runtime.CfJspPage._arrayGetAt(CfJspPage.java:563) at cfdbConfig2ecfc731266051$funcOVERWRITECONFIG.runFunction(C:\ColdFusion9\wwwroot\Apptacular\handlers\cfc\db\dbConfig.cfc:80) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:472) at coldfusion.runtime.UDFMethod$ReturnTypeFilter.invoke(UDFMethod.java:405) at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:368) at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:55) at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:321) at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:220) at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:491) at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:337) at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:2360) at cfhandlerGenerate2ecfm1385738042.runPage(C:\ColdFusion9\wwwroot\Apptacular\handlers\handlerGenerate.cfm:222) at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:231) at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:416) at coldfusion.filter.CfincludeFilter.invoke(CfincludeFilter.java:65) at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:360) at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40) at coldfusion.filter.PathFilter.invoke(PathFilter.java:94) at coldfusion.filter.LicenseFilter.invoke(LicenseFilter.java:27) at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:70) at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28) at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38) at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:46) at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38) at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22) at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62) at coldfusion.filter.RequestThrottleFilter.invoke(RequestThrottleFilter.java:126) at coldfusion.CfmServlet.service(CfmServlet.java:200) at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89) at jrun.servlet.FilterChain.doFilter(FilterChain.java:86) at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42) at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46) at jrun.servlet.FilterChain.doFilter(FilterChain.java:94) at jrun.servlet.FilterChain.service(FilterChain.java:101) at jrun.servlet.ServletInvoker.invoke(ServletInvoker.java:106) at jrun.servlet.JRunInvokerChain.invokeNext(JRunInvokerChain.java:42) at jrun.servlet.JRunRequestDispatcher.invoke(JRunRequestDispatcher.java:286) at jrun.servlet.ServletEngineService.dispatch(ServletEngineService.java:543) at jrun.servlet.http.WebService.invokeRunnable(WebService.java:172) at jrunx.scheduler.ThreadPool$DownstreamMetrics.invokeRunnable(ThreadPool.java:320) at jrunx.scheduler.ThreadPool$ThreadThrottle.invokeRunnable(ThreadPool.java:428) at jrunx.scheduler.ThreadPool$UpstreamMetrics.invokeRunnable(ThreadPool.java:266) at jrunx.scheduler.WorkerThread.run(WorkerThread.java:66) TagContext: [array] 1) [struct] COLUMN: 0 ID: ?? LINE: 80 RAW_TRACE: at cfdbConfig2ecfc731266051$funcOVERWRITECONFIG.runFunction(C:\ColdFusion9\wwwroot\Apptacular\handlers\cfc\db\dbConfig.cfc:80) TEMPLATE: C:\ColdFusion9\wwwroot\Apptacular\handlers\cfc\db\dbConfig.cfc TYPE: CFML 2) [struct] COLUMN: 0 ID: CF_TEMPLATEPROXY LINE: 222 RAW_TRACE: at cfhandlerGenerate2ecfm1385738042.runPage(C:\ColdFusion9\wwwroot\Apptacular\handlers\handlerGenerate.cfm:222) TEMPLATE: C:\ColdFusion9\wwwroot\Apptacular\handlers\handlerGenerate.cfm TYPE: CFML Type: Expression element: CatcaOffice objectType: [object of java.lang.Class] Class Name: java.lang.Class Methods: asSubclass(java.lang.Class) returns java.lang.Class cast(java.lang.Object) returns java.lang.Object desiredAssertionStatus() returns boolean forName(java.lang.String, boolean, java.lang.ClassLoader) returns java.lang.Class forName(java.lang.String) returns java.lang.Class getAnnotation(java.lang.Class) returns java.lang.annotation.Annotation getAnnotations() returns java.lang.annotation.Annotation[] getCanonicalName() returns java.lang.String getClassLoader() returns java.lang.ClassLoader getClasses() returns java.lang.Class[] getComponentType() returns java.lang.Class getConstructor(java.lang.Class[]) returns java.lang.reflect.Constructor getConstructors() returns java.lang.reflect.Constructor[] getDeclaredAnnotations() returns java.lang.annotation.Annotation[] getDeclaredClasses() returns java.lang.Class[] getDeclaredConstructor(java.lang.Class[]) returns java.lang.reflect.Constructor getDeclaredConstructors() returns java.lang.reflect.Constructor[] getDeclaredField(java.lang.String) returns java.lang.reflect.Field getDeclaredFields() returns java.lang.reflect.Field[] getDeclaredMethod(java.lang.String, java.lang.Class[]) returns java.lang.reflect.Method getDeclaredMethods() returns java.lang.reflect.Method[] getDeclaringClass() returns java.lang.Class getEnclosingClass() returns java.lang.Class getEnclosingConstructor() returns java.lang.reflect.Constructor getEnclosingMethod() returns java.lang.reflect.Method getEnumConstants() returns java.lang.Object[] getField(java.lang.String) returns java.lang.reflect.Field getFields() returns java.lang.reflect.Field[] getGenericInterfaces() returns java.lang.reflect.Type[] getGenericSuperclass() returns java.lang.reflect.Type getInterfaces() returns java.lang.Class[] getMethod(java.lang.String, java.lang.Class[]) returns java.lang.reflect.Method getMethods() returns java.lang.reflect.Method[] getModifiers() returns int getName() returns java.lang.String getPackage() returns java.lang.Package getProtectionDomain() returns java.security.ProtectionDomain getResource(java.lang.String) returns java.net.URL getResourceAsStream(java.lang.String) returns java.io.InputStream getSigners() returns java.lang.Object[] getSimpleName() returns java.lang.String getSuperclass() returns java.lang.Class getTypeParameters() returns java.lang.reflect.TypeVariable[] isAnnotation() returns boolean isAnnotationPresent(java.lang.Class) returns boolean isAnonymousClass() returns boolean isArray() returns boolean isAssignableFrom(java.lang.Class) returns boolean isEnum() returns boolean isInstance(java.lang.Object) returns boolean isInterface() returns boolean isLocalClass() returns boolean isMemberClass() returns boolean isPrimitive() returns boolean isSynthetic() returns boolean newInstance() returns java.lang.Object toString() returns java.lang.String ***********************************************************************************\* 

Thanks

Earle
